trigger: none

pool: rg_pool

steps: 
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'RG_Service'
    backendAzureRmStorageAccountName: 'stclassb'
    backendAzureRmContainerName: 'tfstateb'
    backendAzureRmKey: 'classD.tfstate'

- task: TerraformTask@5
  displayName: Terraform fmt
  inputs:
    provider: 'azurerm'
    command: 'custom'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'RG_Service'

- task: TerraformTask@5
  displayName: Terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: Terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'RG_Service'

